apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-oci-example
spec:
  destination:
    namespace: gitops-oci-example
    name: demo
  source:
    path: dev
    repoURL: oci://ghcr.io/jessesuen/gitops-oci-example
    targetRevision: latest
  project: gitops-oci-example
